name: First Workflow
on: [push]

jobs:
  run-my-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my command
        run: |
                echo "Hello, World!"
                echo "This is my first GitHub Action workflow."
  